services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django-backend-dev
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8008"
    volumes:
      - ./backend:/app
    ports:
      - "8008:8008"
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vite-frontend-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

  db:
    image: postgres:16
    container_name: postgres-db-dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata_dev: