services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django-backend
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8008"
    ports:
      - "8008:8008"
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings
      DEBUG: "False"
      ALLOWED_HOSTS: "*"

      # 🔑 Security / Secrets (set these via EB console or ECS task env vars)
      SECRET_KEY: ${SECRET_KEY}

      # 🗄️ Database (RDS connection)
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}

      # Optional: Django DATABASE_URL for dj-database-url
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on: []

volumes:
  static_volume:
  media_volume:
