services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django-backend-dev
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8008"
    volumes:
      - ./backend:/app
    ports:
      - "8008:8008"
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_STATIC_BUCKET_NAME=${AWS_S3_STATIC_BUCKET_NAME}
      - AWS_S3_MEDIA_BUCKET_NAME=${AWS_S3_MEDIA_BUCKET_NAME}
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vite-frontend-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host

  db:
    image: postgres:16
    container_name: postgres-db-dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata_dev: