# Generated by Django 5.2.7 on 2025-10-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='src',
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/media/'),
        ),
    ]
