# Generated by Django 5.2.7 on 2025-10-28 19:36

import photos.models
import photos.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, storage=photos.storage_backends.PrivateMediaStorage(), upload_to=photos.models.user_media_path),
        ),
    ]
